# Generated by Django 4.2.20 on 2025-04-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='歌手姓名')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='国籍')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='歌名')),
                ('album', models.CharField(blank=True, max_length=200, null=True, verbose_name='专辑')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发行日期')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='风格')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='lyrics.artist', verbose_name='歌手')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='歌词内容')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyric', to='lyrics.song', verbose_name='所属歌曲')),
            ],
        ),
    ]
